[project]
name = "mtg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "basedpyright>=1.28.5",
    "black>=25.1.0",
    "ipython>=9.1.0",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "ruff>=0.11.6",
]
